# Generated by Django 4.2.7 on 2026-03-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='business password'),
        ),
    ]
