# Generated by Django 4.2.7 on 2026-04-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_business_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='rejection reason'),
        ),
        migrations.AddField(
            model_name='business',
            name='suspension_reason',
            field=models.TextField(blank=True, verbose_name='suspension reason'),
        ),
    ]
