# Generated by Django 4.2.7 on 2026-04-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_booking_date_order_booking_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cash_on_delivery', max_length=50),
        ),
    ]
