# Generated by Django 4.2.7 on 2026-04-01 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SSME Market', max_length=200)),
                ('site_description', models.TextField(default='Small and Medium Enterprises Marketplace')),
                ('contact_email', models.EmailField(default='admin@ssme.com', max_length=254)),
                ('contact_phone', models.CharField(default='+233 20 123 4567', max_length=20)),
                ('contact_address', models.TextField(default='Accra, Ghana')),
                ('site_url', models.URLField(default='https://ssme.com')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default='Site is under maintenance. Please check back later.')),
                ('allow_user_registration', models.BooleanField(default=True)),
                ('allow_business_registration', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('auto_approve_businesses', models.BooleanField(default=False)),
                ('max_businesses_per_user', models.IntegerField(default=1)),
                ('business_approval_required', models.BooleanField(default=True)),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.CharField(blank=True, max_length=200)),
                ('email_host_password', models.CharField(blank=True, max_length=200)),
                ('default_from_email', models.EmailField(default='noreply@ssme.com', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_auth_enabled', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.IntegerField(default=30)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('lockout_duration_minutes', models.IntegerField(default=15)),
                ('password_min_length', models.IntegerField(default=8)),
                ('password_require_uppercase', models.BooleanField(default=True)),
                ('password_require_lowercase', models.BooleanField(default=True)),
                ('password_require_numbers', models.BooleanField(default=True)),
                ('password_require_symbols', models.BooleanField(default=True)),
                ('password_history_count', models.IntegerField(default=5)),
                ('concurrent_sessions_allowed', models.IntegerField(default=3)),
                ('remember_me_days', models.IntegerField(default=30)),
                ('api_rate_limit', models.IntegerField(default=100)),
                ('api_timeout_minutes', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('order_notifications', models.BooleanField(default=True)),
                ('business_registration_notifications', models.BooleanField(default=True)),
                ('user_registration_notifications', models.BooleanField(default=True)),
                ('review_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('push_notifications_enabled', models.BooleanField(default=True)),
                ('welcome_email_template', models.TextField(blank=True)),
                ('business_approval_template', models.TextField(blank=True)),
                ('order_confirmation_template', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup_enabled', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('backup_retention_days', models.IntegerField(default=30)),
                ('backup_location', models.CharField(choices=[('local', 'Local Storage'), ('cloud', 'Cloud Storage'), ('both', 'Both')], default='cloud', max_length=20)),
                ('cloud_provider', models.CharField(blank=True, default='aws', max_length=50)),
                ('cloud_bucket', models.CharField(blank=True, max_length=200)),
                ('cloud_access_key', models.CharField(blank=True, max_length=200)),
                ('cloud_secret_key', models.CharField(blank=True, max_length=200)),
                ('last_backup_time', models.DateTimeField(blank=True, null=True)),
                ('last_backup_size', models.BigIntegerField(blank=True, null=True)),
                ('backup_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('running', 'Running'), ('never', 'Never')], default='never', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Settings',
                'verbose_name_plural': 'Backup Settings',
            },
        ),
    ]
